prometheus:
  enabled: false

strim:
  image: thavlik/strim:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "64Mi"
    limits:
      memory: "128Mi"
  target:
    enabled: false # in-memory only
    bucket: ""
    endpoint: ""
    region: "us-east-1"
    secret: ""
    keyPrefix: ""

operator:
  image: thavlik/strim-operator:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "32Mi"
    limits:
      memory: "64Mi"