apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app: {{ .Release.Name }}-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app: {{ .Release.Name }}-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "strim.beebs.dev"
    resources:
      - strims
      - strims/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app: {{ .Release.Name }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-operator
    namespace: {{ .Release.Namespace }}
---
{{- $image := printf "%s%s" .Values.registry .Values.operator.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
      - name: strim-operator
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.operator.resources }}
        resources:
{{ toYaml .Values.operator.resources | indent 10 }}
    {{- end }}
        command:
          - strim-operator
          - manage-strims
{{- if .Values.prometheus.enabled }}
        ports:
        - containerPort: 2112
          protocol: TCP
          name: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 2112
        livenessProbe:
          httpGet:
            path: /healthz
            port: 2112
{{- else }}
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/ready
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
        env:
        - name: SERVICE_NAME
          value: strim-operator
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.operator.logLevel }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{ include "synapse.metrics-env" . | indent 8 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  podMetricsEndpoints:
  - port: metrics
{{- end }}
