strim:
  image: thavlik/strim:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "64Mi"
    limits:
      memory: "128Mi"
  target:
    bucket: ""
    endpoint: ""
    region: "us-east-1"
    secret: ""
    keyPrefix: ""