strim:
  image: thavlik/strim:latest
  imagePullPolicy: Always
  replicas: 1
  logLevel: debug
  resources:
    requests: 
      memory: "64Mi"
    limits:
      memory: "128Mi"
  target:
    enabled: true
    bucket: gibstrim
    endpoint: https://nyc3.digitaloceanspaces.com
    region: "nyc3"
    secret: spaces-cred
    keyPrefix: "live/"